"""image filename and preprocessed added

Revision ID: 0150ab515032
Revises: 588de7c7714b
Create Date: 2025-06-26 12:10:15.944815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0150ab515032'
down_revision: Union[str, None] = '588de7c7714b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('images', sa.Column('preprocessed', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'preprocessed')
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###
