"""renamed mapping_report_id in image

Revision ID: 045c7da42552
Revises: 0150ab515032
Create Date: 2025-06-26 13:58:21.978904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045c7da42552'
down_revision: Union[str, None] = '0150ab515032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('mapping_report_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_images_report_id'), table_name='images')
    op.create_index(op.f('ix_images_mapping_report_id'), 'images', ['mapping_report_id'], unique=False)
    op.drop_constraint(op.f('images_report_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'mapping_reports', ['mapping_report_id'], ['id'])
    op.drop_column('images', 'report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_report_id_fkey'), 'images', 'mapping_reports', ['report_id'], ['id'])
    op.drop_index(op.f('ix_images_mapping_report_id'), table_name='images')
    op.create_index(op.f('ix_images_report_id'), 'images', ['report_id'], unique=False)
    op.drop_column('images', 'mapping_report_id')
    # ### end Alembic commands ###
