"""Thermal Data update

Revision ID: 0cf489ea388e
Revises: 6b16f5299d92
Create Date: 2025-07-21 16:28:42.490329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf489ea388e'
down_revision: Union[str, None] = '6b16f5299d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thermal_data', sa.Column('counterpart_id', sa.Integer(), nullable=True))
    op.add_column('thermal_data', sa.Column('counterpart_scale', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'thermal_data', 'images', ['counterpart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thermal_data', type_='foreignkey')
    op.drop_column('thermal_data', 'counterpart_scale')
    op.drop_column('thermal_data', 'counterpart_id')
    # ### end Alembic commands ###
