"""changes thermal matrix to matrix path

Revision ID: 1400ead1405b
Revises: 8017068387c2
Create Date: 2025-07-28 08:32:20.867930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1400ead1405b'
down_revision: Union[str, None] = '8017068387c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thermal_data', sa.Column('temp_matrix_path', sa.String(), nullable=True))
    op.drop_column('thermal_data', 'temp_matrix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thermal_data', sa.Column('temp_matrix', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('thermal_data', 'temp_matrix_path')
    # ### end Alembic commands ###
