"""adjusted map data

Revision ID: 25df61635b94
Revises: 55882060c29a
Create Date: 2025-07-15 10:15:16.968638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25df61635b94'
down_revision: Union[str, None] = '55882060c29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('mapping_report_id', sa.Integer(), nullable=False))
    op.add_column('maps', sa.Column('odm', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_maps_report_id'), table_name='maps')
    op.create_index(op.f('ix_maps_mapping_report_id'), 'maps', ['mapping_report_id'], unique=False)
    op.drop_constraint(op.f('maps_report_id_fkey'), 'maps', type_='foreignkey')
    op.create_foreign_key(None, 'maps', 'mapping_reports', ['mapping_report_id'], ['id'])
    op.drop_column('maps', 'status')
    op.drop_column('maps', 'report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('maps', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'maps', type_='foreignkey')
    op.create_foreign_key(op.f('maps_report_id_fkey'), 'maps', 'mapping_reports', ['report_id'], ['id'])
    op.drop_index(op.f('ix_maps_mapping_report_id'), table_name='maps')
    op.create_index(op.f('ix_maps_report_id'), 'maps', ['report_id'], unique=False)
    op.drop_column('maps', 'odm')
    op.drop_column('maps', 'mapping_report_id')
    # ### end Alembic commands ###
