"""changed some weather properties

Revision ID: 55882060c29a
Revises: b6daa82c141d
Create Date: 2025-07-10 13:32:01.021793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55882060c29a'
down_revision: Union[str, None] = 'b6daa82c141d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('mapping_report_id', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('open_weather_id', sa.String(), nullable=True))
    op.add_column('weather', sa.Column('description', sa.String(), nullable=True))
    op.add_column('weather', sa.Column('pressure', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_weather_report_id'), table_name='weather')
    op.create_index(op.f('ix_weather_mapping_report_id'), 'weather', ['mapping_report_id'], unique=False)
    op.drop_constraint(op.f('weather_report_id_fkey'), 'weather', type_='foreignkey')
    op.create_foreign_key(None, 'weather', 'mapping_reports', ['mapping_report_id'], ['id'])
    op.drop_column('weather', 'report_id')
    op.drop_column('weather', 'air_pressure')
    op.drop_column('weather', 'coord')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('coord', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('air_pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weather', type_='foreignkey')
    op.create_foreign_key(op.f('weather_report_id_fkey'), 'weather', 'mapping_reports', ['report_id'], ['id'])
    op.drop_index(op.f('ix_weather_mapping_report_id'), table_name='weather')
    op.create_index(op.f('ix_weather_report_id'), 'weather', ['report_id'], unique=False)
    op.drop_column('weather', 'pressure')
    op.drop_column('weather', 'description')
    op.drop_column('weather', 'open_weather_id')
    op.drop_column('weather', 'mapping_report_id')
    # ### end Alembic commands ###
