"""added missing index

Revision ID: 6b16f5299d92
Revises: f07e5e6859dd
Create Date: 2025-07-18 14:41:14.974516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b16f5299d92'
down_revision: Union[str, None] = 'f07e5e6859dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_map_elements_image_id'), 'map_elements', ['image_id'], unique=False)
    op.alter_column('maps', 'mapping_report_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maps', 'mapping_report_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_map_elements_image_id'), table_name='map_elements')
    # ### end Alembic commands ###
