"""adding missing boolean in thermal data

Revision ID: 8017068387c2
Revises: 0cf489ea388e
Create Date: 2025-07-21 16:58:27.470288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8017068387c2'
down_revision: Union[str, None] = '0cf489ea388e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thermal_data', sa.Column('temp_embedded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thermal_data', 'temp_embedded')
    # ### end Alembic commands ###
