"""altered the mapping data

Revision ID: b6daa82c141d
Revises: 9597de07ae2f
Create Date: 2025-07-09 12:21:27.511736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6daa82c141d'
down_revision: Union[str, None] = '9597de07ae2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_data', sa.Column('rel_altitude_method', sa.String(), nullable=True))
    op.add_column('mapping_data', sa.Column('altitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_data', 'altitude')
    op.drop_column('mapping_data', 'rel_altitude_method')
    # ### end Alembic commands ###
