"""added WebODm project ID

Revision ID: cffaa3b4b9e6
Revises: 1400ead1405b
Create Date: 2025-08-06 11:26:37.204147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffaa3b4b9e6'
down_revision: Union[str, None] = '1400ead1405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_reports', sa.Column('webodm_project_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_reports', 'webodm_project_id')
    # ### end Alembic commands ###
