"""map bounds added

Revision ID: f07e5e6859dd
Revises: 25df61635b94
Create Date: 2025-07-15 10:31:22.545984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f07e5e6859dd'
down_revision: Union[str, None] = '25df61635b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('bounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'bounds')
    # ### end Alembic commands ###
