# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_segment.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_segment.proto',
  package='map_segment',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11map_segment.proto\x12\x0bmap_segment\"\xf7\x03\n\x03map\x12-\n\rcurrent_frame\x18\x01 \x01(\x0b\x32\x16.map_segment.map.Mat44\x12,\n\tkeyframes\x18\x02 \x03(\x0b\x32\x19.map_segment.map.keyframe\x12$\n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32\x15.map_segment.map.edge\x12,\n\tlandmarks\x18\x04 \x03(\x0b\x32\x19.map_segment.map.landmark\x12\x17\n\x0flocal_landmarks\x18\x05 \x03(\r\x12&\n\x08messages\x18\x06 \x03(\x0b\x32\x14.map_segment.map.msg\x12/\n\x0c\x64\x65nse_points\x18\x07 \x03(\x0b\x32\x19.map_segment.map.landmark\x1a<\n\x08keyframe\x12\n\n\x02id\x18\x01 \x01(\r\x12$\n\x04pose\x18\x02 \x01(\x0b\x32\x16.map_segment.map.Mat44\x1a \n\x04\x65\x64ge\x12\x0b\n\x03id0\x18\x01 \x01(\r\x12\x0b\n\x03id1\x18\x02 \x01(\r\x1a\x35\n\x08landmark\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06\x63oords\x18\x02 \x03(\x01\x12\r\n\x05\x63olor\x18\x03 \x03(\x01\x1a\x15\n\x05Mat44\x12\x0c\n\x04pose\x18\x01 \x03(\x01\x1a\x1f\n\x03msg\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0b\n\x03txt\x18\x02 \x01(\tb\x06proto3'
)




_MAP_KEYFRAME = _descriptor.Descriptor(
  name='keyframe',
  full_name='map_segment.map.keyframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='map_segment.map.keyframe.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='map_segment.map.keyframe.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=393,
)

_MAP_EDGE = _descriptor.Descriptor(
  name='edge',
  full_name='map_segment.map.edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id0', full_name='map_segment.map.edge.id0', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id1', full_name='map_segment.map.edge.id1', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=427,
)

_MAP_LANDMARK = _descriptor.Descriptor(
  name='landmark',
  full_name='map_segment.map.landmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='map_segment.map.landmark.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coords', full_name='map_segment.map.landmark.coords', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='map_segment.map.landmark.color', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=482,
)

_MAP_MAT44 = _descriptor.Descriptor(
  name='Mat44',
  full_name='map_segment.map.Mat44',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='map_segment.map.Mat44.pose', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=505,
)

_MAP_MSG = _descriptor.Descriptor(
  name='msg',
  full_name='map_segment.map.msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='map_segment.map.msg.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txt', full_name='map_segment.map.msg.txt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=538,
)

_MAP = _descriptor.Descriptor(
  name='map',
  full_name='map_segment.map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_frame', full_name='map_segment.map.current_frame', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyframes', full_name='map_segment.map.keyframes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edges', full_name='map_segment.map.edges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='map_segment.map.landmarks', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_landmarks', full_name='map_segment.map.local_landmarks', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messages', full_name='map_segment.map.messages', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dense_points', full_name='map_segment.map.dense_points', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MAP_KEYFRAME, _MAP_EDGE, _MAP_LANDMARK, _MAP_MAT44, _MAP_MSG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=538,
)

_MAP_KEYFRAME.fields_by_name['pose'].message_type = _MAP_MAT44
_MAP_KEYFRAME.containing_type = _MAP
_MAP_EDGE.containing_type = _MAP
_MAP_LANDMARK.containing_type = _MAP
_MAP_MAT44.containing_type = _MAP
_MAP_MSG.containing_type = _MAP
_MAP.fields_by_name['current_frame'].message_type = _MAP_MAT44
_MAP.fields_by_name['keyframes'].message_type = _MAP_KEYFRAME
_MAP.fields_by_name['edges'].message_type = _MAP_EDGE
_MAP.fields_by_name['landmarks'].message_type = _MAP_LANDMARK
_MAP.fields_by_name['messages'].message_type = _MAP_MSG
_MAP.fields_by_name['dense_points'].message_type = _MAP_LANDMARK
DESCRIPTOR.message_types_by_name['map'] = _MAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

map = _reflection.GeneratedProtocolMessageType('map', (_message.Message,), {

  'keyframe' : _reflection.GeneratedProtocolMessageType('keyframe', (_message.Message,), {
    'DESCRIPTOR' : _MAP_KEYFRAME,
    '__module__' : 'map_segment_pb2'
    # @@protoc_insertion_point(class_scope:map_segment.map.keyframe)
    })
  ,

  'edge' : _reflection.GeneratedProtocolMessageType('edge', (_message.Message,), {
    'DESCRIPTOR' : _MAP_EDGE,
    '__module__' : 'map_segment_pb2'
    # @@protoc_insertion_point(class_scope:map_segment.map.edge)
    })
  ,

  'landmark' : _reflection.GeneratedProtocolMessageType('landmark', (_message.Message,), {
    'DESCRIPTOR' : _MAP_LANDMARK,
    '__module__' : 'map_segment_pb2'
    # @@protoc_insertion_point(class_scope:map_segment.map.landmark)
    })
  ,

  'Mat44' : _reflection.GeneratedProtocolMessageType('Mat44', (_message.Message,), {
    'DESCRIPTOR' : _MAP_MAT44,
    '__module__' : 'map_segment_pb2'
    # @@protoc_insertion_point(class_scope:map_segment.map.Mat44)
    })
  ,

  'msg' : _reflection.GeneratedProtocolMessageType('msg', (_message.Message,), {
    'DESCRIPTOR' : _MAP_MSG,
    '__module__' : 'map_segment_pb2'
    # @@protoc_insertion_point(class_scope:map_segment.map.msg)
    })
  ,
  'DESCRIPTOR' : _MAP,
  '__module__' : 'map_segment_pb2'
  # @@protoc_insertion_point(class_scope:map_segment.map)
  })
_sym_db.RegisterMessage(map)
_sym_db.RegisterMessage(map.keyframe)
_sym_db.RegisterMessage(map.edge)
_sym_db.RegisterMessage(map.landmark)
_sym_db.RegisterMessage(map.Mat44)
_sym_db.RegisterMessage(map.msg)


# @@protoc_insertion_point(module_scope)
